<?php

namespace AppBundle\Repository;

/**
 * SavedImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavedImageRepository extends \Doctrine\ORM\EntityRepository
{


}
